# Generated by Django 5.0.6 on 2024-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
