# Generated by Django 4.1.7 on 2024-06-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('tax_type', models.CharField(choices=[('16% VAT', '16% VAT'), ('EXEMPT', 'EXEMPT'), ('2% CATERING', '2% CATERING LEVY'), ('14% VAT', '14% VAT')], max_length=20)),
                ('SKU', models.CharField(max_length=10)),
                ('marked_price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('16% VAT', '16% VAT'), ('EXEMPT', 'EXEMPT'), ('2% CATERING', '2% CATERING LEVY'), ('14% VAT', '14% VAT')], max_length=20)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('16% VAT', '16% VAT'), ('EXEMPT', 'EXEMPT'), ('2% CATERING', '2% CATERING LEVY'), ('14% VAT', '14% VAT')], max_length=20)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.item')),
            ],
        ),
    ]
