# Generated by Django 5.0.6 on 2024-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
