# Generated by Django 5.0.6 on 2024-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
