# Generated by Django 5.0.6 on 2024-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_supplier_rename_item_name_purchase_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
